### ISSUE TITLE
Problem with Ajax

### ISSUE THREAD

**Issue by Dragonwolf** [mshahbazsaleem/jsShare#1]
I have a question, I've tried to use what you have but when I use ajax in the application as well I have to press F5 for the social buttons to appear. What do you think may be the problem?

**Comment by mshahbazsaleem** [comment]
Please post your question under comments section here http://www.egrappler.com/jquery-social-media-share-plugin-jsshare/. This will help other users as well, also you may already find the answer to your question in the comments section

**Comment by mshahbazsaleem** [comment]
Also can you show me how you are using the plugin with ajax?
